#if UNITY_EDITOR
using System.IO;
using System.Linq;
using UnityEditor;

public static class SoundIdsCodeGenerator
{
    public static void Generate()
    {
        var path = "Assets/Application/Audio/Generated/SoundIds.cs";
        Directory.CreateDirectory(Path.GetDirectoryName(path));

        var catalog = AssetDatabase.FindAssets("t:SoundCatalog")
            .Select(g => AssetDatabase.LoadAssetAtPath<SoundCatalog>(AssetDatabase.GUIDToAssetPath(g)))
            .FirstOrDefault();
        if (catalog == null) return;

        string Sanitize(string s)
        {
            var x = s.Replace("/", "_").Replace("-", "_").Replace(" ", "_");
            return new string(x.Where(ch => char.IsLetterOrDigit(ch) || ch == '_').ToArray());
        }

        var consts = catalog.entries
            .Where(e => e != null && !string.IsNullOrEmpty(e.id))
            .Select(e => $"    public const string {Sanitize(e.id)} = \"{e.id}\";");

        var code =
            $@"// <auto-generated/>
public static class SoundIds
{{
{string.Join("\n", consts)}
}}";

        File.WriteAllText(path, code);
        AssetDatabase.Refresh();
    }
}
#endif