using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

[CreateAssetMenu(menuName = "Statistics/Statistics Catalogue", fileName = "StatisticsCatalogue")]
public sealed class StatisticsCatalogue : ScriptableObject
{
    [Serializable]
    public class Entry
    {
        [Tooltip("Unique ID, e.g. core/wins, economy/coins_collected")]
        public string id;
    }

    public List<Entry> entries = new();
#if UNITY_EDITOR
    [Header("Code Generation")] [Tooltip("Absolute or project-relative path to the generated constants file.")]
    public string generatedFilePath = "Assets/Application/Modules/GeneralStatistics/Generated/";
    public string generatedFileName = "StatisticsIds.cs";

    [ContextMenu("Generate StatisticsIds.cs")]
    public void GenerateStatIds()
    {
        if (entries == null || entries.Count == 0)
        {
            Debug.LogWarning("[StatisticsCatalog] No entries to generate StatIds from.");
            return;
        }

        var path = generatedFilePath + generatedFileName;
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        string Sanitize(string s)
        {
            if (string.IsNullOrWhiteSpace(s)) return "_EMPTY_";
            var x = s.Replace("/", "_")
                .Replace("-", "_")
                .Replace(" ", "_")
                .Replace(".", "_");
            var filtered = new string(x.Where(ch => char.IsLetterOrDigit(ch) || ch == '_').ToArray());
            if (filtered.Length > 0 && char.IsDigit(filtered[0])) filtered = "_" + filtered;
            return filtered.ToUpperInvariant();
        }

        var consts = entries
            .Where(e => e != null && !string.IsNullOrEmpty(e.id))
            .Select(e =>
            {
                var name = Sanitize(e.id);
                return $"\tpublic const string {name} = \"{e.id}\";";
            });

        var code = $@"// <auto-generated/>
// Generated from StatisticsCatalog '{name}'. Do not edit manually.
public static class StatisticsIds
{{
{string.Join("\n", consts)}
}}";

        File.WriteAllText(path, code);
        AssetDatabase.Refresh();
        Debug.Log($"[StatisticsCatalog] Generated StatisticsIds.cs at: {path}");
    }

    public static string Normalize(string id) =>
        string.IsNullOrWhiteSpace(id) ? string.Empty : id.Trim();
#endif
}